---
- name: enable pseudo-forge
  lineinfile:
    dest: /home/douglas/.bashrc
    state: present
    line: "alias reforge='cd /home/douglas/playbook-{{ project }}/ && git pull && sudo ansible-galaxy install -r dependencies.yml --force && ansible-playbook playbook.yml -i hosts/{{ environment_tier }}'"
    insertafter: EOF